on: workflow_dispatch 

name: AzureACR

jobs: 
  azureacr: 
    runs-on: ubuntu-latest
    steps: 
      - name: Log in with Azure 
        uses: azure/login@v1
        with:    
          creds: '${{ secrets.AZURE_CREDENTIALS }}' 
          
      - name: ACR Login
        uses: docker/login-action@v2
        with:
          registry: learacr311.azurecr.io
          username: learacr311 
          password: ${{ secrets.ACR_PWD}}
          
      - name: Show repos from ACR
        uses: azure/CLI@v1
        with:
          azcliversion: latest 
          inlineScript: | 
            echo "Show the current Repos"
            az acr list -o table
