on: workflow_dispatch 

name: AzureACI

jobs: 
  azureacr: 
    runs-on: ubuntu-latest
    steps: 
      - name: Log in with Azure 
        uses: azure/login@v1
        with:    
          creds: '${{ secrets.AZURE_CREDENTIALS }}' 
                    
      - name: Azure ACI
        uses: azure/CLI@v1
        with:
          azcliversion: latest 
          inlineScript: | 
            echo "Create an Azure Container Instance"
            az container create -g ${{vars.RG_NAME}} --name mycontainerinstance --image learacr311.azurecr.io/nginx:mycopy --registry-password ${{secrets.ACR_PWD}} --registry-username learacr311 --ip-address public --dns-name-label learacr311
