on: workflow_dispatch 

name: AzureKeyVault

env:
  kvname: learnkeyvault311
  secretname: amdalumpines

jobs: 
  access-keyvault: 
    runs-on: ubuntu-latest
    steps: 
      - name: Log in with Azure 
        uses: azure/login@v1
        with:    
          creds: '${{ secrets.AZURE_CREDENTIALS }}' 
          
          
      - name: Access secret from Key Vault
        uses: azure/CLI@v1
        with:
          azcliversion: latest 
          inlineScript: | 
            echo "Lets find the secret"
            az keyvault secret show --vault-name ${{ env.kvname }} -n ${{ env.secretname }} --query value
